// Server-rendered HTML templates for PO / Invoice documents (Spec §6.8).

const money = (n: number, currency = 'INR') =>
  new Intl.NumberFormat('en-IN', { style: 'currency', currency }).format(n);

const styles = `
  * { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a2e; }
  body { padding: 0; margin: 0; font-size: 13px; }
  .wrap { padding: 8px 4px; }
  .head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #4f46e5; padding-bottom: 16px; margin-bottom: 24px; }
  .brand { font-size: 22px; font-weight: 800; color: #4f46e5; letter-spacing: -0.5px; }
  .doc-title { font-size: 26px; font-weight: 700; text-align: right; }
  .muted { color: #6b7280; }
  .meta { display: flex; justify-content: space-between; margin-bottom: 24px; gap: 32px; }
  .meta h4 { margin: 0 0 6px; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #6b7280; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th { background: #f3f4f6; text-align: left; padding: 10px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
  td { padding: 10px; border-bottom: 1px solid #e5e7eb; }
  .right { text-align: right; }
  .totals { width: 280px; margin-left: auto; }
  .totals td { border: none; padding: 6px 10px; }
  .grand { font-size: 17px; font-weight: 800; border-top: 2px solid #4f46e5 !important; color: #4f46e5; }
  .badge { display: inline-block; padding: 4px 12px; border-radius: 999px; background: #eef2ff; color: #4f46e5; font-weight: 700; font-size: 11px; }
  .foot { margin-top: 40px; color: #9ca3af; font-size: 11px; border-top: 1px solid #e5e7eb; padding-top: 12px; }
`;

export interface DocLine {
  description: string;
  quantity: number;
  unitPrice: number;
  taxRate: number;
  lineTotal: number;
}

export interface DocModel {
  type: 'PURCHASE ORDER' | 'INVOICE';
  number: string;
  status: string;
  date: Date;
  dueDate?: Date | null;
  org: { name: string; gstin?: string | null };
  party: { name: string; email?: string | null; gstin?: string | null; address?: string | null };
  lines: DocLine[];
  subtotal: number;
  taxTotal: number;
  grandTotal: number;
  currency: string;
}

export function renderDocumentHtml(m: DocModel): string {
  const rows = m.lines
    .map(
      (l) => `<tr>
        <td>${escapeHtml(l.description)}</td>
        <td class="right">${l.quantity}</td>
        <td class="right">${money(l.unitPrice, m.currency)}</td>
        <td class="right">${l.taxRate}%</td>
        <td class="right">${money(l.lineTotal, m.currency)}</td>
      </tr>`,
    )
    .join('');

  return `<!doctype html><html><head><meta charset="utf-8"><style>${styles}</style></head>
  <body><div class="wrap">
    <div class="head">
      <div>
        <div class="brand">VendorBridge</div>
        <div class="muted">${escapeHtml(m.org.name)}</div>
        ${m.org.gstin ? `<div class="muted">GSTIN: ${escapeHtml(m.org.gstin)}</div>` : ''}
      </div>
      <div>
        <div class="doc-title">${m.type}</div>
        <div class="right muted">#${escapeHtml(m.number)}</div>
        <div class="right"><span class="badge">${escapeHtml(m.status)}</span></div>
      </div>
    </div>

    <div class="meta">
      <div>
        <h4>${m.type === 'INVOICE' ? 'Bill To' : 'Vendor'}</h4>
        <div><strong>${escapeHtml(m.party.name)}</strong></div>
        ${m.party.email ? `<div class="muted">${escapeHtml(m.party.email)}</div>` : ''}
        ${m.party.address ? `<div class="muted">${escapeHtml(m.party.address)}</div>` : ''}
        ${m.party.gstin ? `<div class="muted">GSTIN: ${escapeHtml(m.party.gstin)}</div>` : ''}
      </div>
      <div class="right">
        <h4>Details</h4>
        <div>Date: ${m.date.toLocaleDateString('en-IN')}</div>
        ${m.dueDate ? `<div>Due: ${m.dueDate.toLocaleDateString('en-IN')}</div>` : ''}
      </div>
    </div>

    <table>
      <thead><tr>
        <th>Description</th><th class="right">Qty</th><th class="right">Unit Price</th>
        <th class="right">Tax</th><th class="right">Amount</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table>

    <table class="totals">
      <tr><td>Subtotal</td><td class="right">${money(m.subtotal, m.currency)}</td></tr>
      <tr><td>Tax</td><td class="right">${money(m.taxTotal, m.currency)}</td></tr>
      <tr><td class="grand">Total</td><td class="right grand">${money(m.grandTotal, m.currency)}</td></tr>
    </table>

    <div class="foot">
      Generated by VendorBridge · This is a system-generated document.
      ${m.type === 'INVOICE' ? 'Pay securely via the VendorBridge portal.' : ''}
    </div>
  </div></body></html>`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => {
    const map: Record<string, string> = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#39;',
    };
    return map[c];
  });
}
